baseurl = "https://jihoonog.github.io/"
languageCode = "en-us"
theme = "hello-friend-ng"



[params]
  dateform        = "Oct 7, 2006"
  dateformShort   = "Oct 7"
  dateformNum     = "2019-10-07"
  dateformNumTime = "2019-02 15:04 -0700"
  
  [[params.social]]
    name = "github"
    url = "https://github.com/jihoonog"
  # Metadata mostly used in document's head
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  # contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Jihoon Og"
    subtitle = "Computing Science Student"
    description = "Honors Computing Science Student"
    keywords = "homepage, blog, science, informatics, development, programming"
    homeSubtitle = "Honors Computing Science Student"
    
    # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
    
    [languages.en.params.logo]
      logoText = "/home/Jihoon_Og"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Resume"
        url = "/Resume/resume.pdf"

# And you can even create generic menu
#[menu]
  #[[menu.main]]
  #  identifier = "about"
  #  name       = "About"
  #  url        = "/about"
  #[[menu.main]]
  #  identifier = "blog"
  #  name       = "Blog"
  #  url        = "/posts"


# Can the NLP model described in the seminar work well for other languages with different grammer structures and morphology? Basically can this model work well Chinese which is an analytic language as well as Thai as well as French and English?
